### PR TITLE
DM-18895 proposal: apply upstream bugfix

### PR DESCRIPTION
**Pull request by PaulPrice**
This is a proposal for DM-18895; this fix, combined with fixes to jointcal (larger index types and force Eigen to use them) gets us past the segfault.

### CODE REVIEW

**Comment by timj** [comment]
Would it be useful to update from upstream and apply our patches on top of that so that it's easier to send the fixes back?

**Comment by PaulPrice** [comment]
No, this repo looks very different from upstream, so we share no git history.

**Comment by parejkoj** [comment]
At the time I took over jointcal (née meas_simastrom), it had a more complicated symlinked thing to get the necessary bits out of SuiteSparse. SuiteSparse is a huge package, and jointcal only needs the cholmod component, hence this package which extracted just those necessary bits. That was done on a version from several years ago, and updating it may be tricky (but might also be worthwhile for bugfixes, I don't know).

**Comment by PaulPrice** [comment]
I reviewed the change log for SuiteSparse as a whole and cholmod in particular, and found that this was the only bugfix. There are manini-kine non-functional changes and they changed the license.

**Review by parejkoj — APPROVED** [review]

**Comment by PaulPrice** [comment]
Replaced by formal submission in #3.

**Pull request closed without merging**
